apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_DB: "{{ .Values.postgres.database }}"
  POSTGRES_USER: "{{ .Values.postgres.username }}"
  POSTGRES_PASSWORD: "{{ .Values.postgres.password }}"

